---
title: "Brain Expression Signatures in Alzheimer's Disease"
author: "Dr Stephen Newhouse"
date: "03/02/2015"
output: html_document
---

***********************************

## getGEO

Getting the data in one place...

**********

#### GSE15222
#### Genetic Control of Human Brain Transcript Expression in Alzheimer Disease  
- http://www.sciencedirect.com/science/article/pii/S0002929709001086  

**ABSTRACT**  

> We recently surveyed the relationship between the human brain transcriptome and genome in a series of neuropathologically normal postmortem samples. We have now analyzed additional samples with a confirmed pathologic diagnosis of late-onset Alzheimer disease (LOAD; final n = 188 controls, 176 cases). Nine percent of the cortical transcripts that we analyzed had expression profiles correlated with their genotypes in the combined cohort, and approximately 5% of transcripts had SNP-transcript relationships that could distinguish LOAD samples. Two of these transcripts have been previously implicated in LOAD candidate-gene SNP-expression screens. This study shows how the relationship between common inherited genetic variants and brain transcript expression can be used in the study of human brain disorders. We suggest that studying the transcriptome as a quantitative endo-phenotype has greater power for discovering risk SNPs influencing expression than the use of discrete diagnostic categories such as presence or absence of disease.

```{r getGEO_GSE15222, eval=FALSE}

################################################################
#  Get Data
library(Biobase)
library(GEOquery)
library(limma)

################
# set working dir
setwd("/media/sjnewhouse/D/ad_brain_expression/")

###############################################
# load series and platform data from GEO
#
gset <- getGEO("GSE15222", GSEMatrix =TRUE,AnnotGPL=TRUE,getGPL=TRUE)
ls

if (length(gset) > 1) idx <- grep("GPL2700", attr(gset, "names")) else idx <- 1
gset <- gset[[idx]]

#################
# save
save(gset, file="./data/GSE15222_webster2009.RData",compress=TRUE)

#######################
# add to .gitignore
system( paste( "echo \"./data/GSE15222_webster2009.RData\" >> .gitignore",sep="" ) )
system( paste( "git add --all ./.gitignore",sep="" ) )
system( paste( "git add --all ./*",sep="" ) )
system( paste( "git rm --cached data/GSE15222_webster2009.RData,sep="" ) )

```

***********************************
